### ISSUE TITLE
Rationale update for all basleines

### ISSUE THREAD

**Issue by snarve** [cisagov/ScubaGoggles#227]
# 💡 Summary #

This epic covers the rationale updates for all the baselines

## Implementation notes ##

Update rationale statements for all the baselines

- [ ] Chat - https://github.com/cisagov/ScubaGoggles/issues/229
- [x] Sites
- [x] Meet
- [x] Calendar
- [ ] Gmail - https://github.com/cisagov/ScubaGoggles/issues/228
- [ ] Common Controls - https://github.com/cisagov/ScubaGoggles/issues/230
- [ ] Groups - https://github.com/cisagov/ScubaGoggles/issues/231
- [ ] Drive Docs - https://github.com/cisagov/ScubaGoggles/issues/232

## Acceptance criteria ##

- [ ] All baselines have updated rationale
