### ISSUE TITLE
Review newly added GWS Assured controls

### ISSUE THREAD

**Issue by snarve** [cisagov/ScubaGoggles#331]
# 💡 Summary #

This epic is to handle an overall review of all the newly added controls made available in the general GWS console, some of which were previously available only as add-on features. This epic will include details on if and how these controls may affect the existing baselines. 

Add any issues related to reviewing these controls under this epic.  

### Acceptance criteria

- [ ] Revisit whether the Assured Controls and licenses are still required for data process settings 
- [ ] Write up baseline updates for Assured Control baselines
- [ ] Write up baseline updates for 15.3 new policy

**Comment by prodjom** [comment]
Assured Controls Plus SCB add-in guidance will be targeted for a future release after Eel release
