### ISSUE TITLE
Tracking Initial Completion of GWS Providers/Rego

### ISSUE THREAD

**Issue by amart241** [cisagov/ScubaGoggles#43]
Making this checklist for the to keep track of completed Providers/Rego

## Providers (Inside provider.py)
- [x] Google Calendar 
- [x] Groups for Business
- [x] Gmail (Missing 2.20 - 2.27 May need to mark as N/A) 
- [x] Google Chat and Hangouts
- [x] Google Drive and Docs 
- [x] Google Meet 
- [x] Google Sites 
- [x] GWS Common Controls
- [x] ~#50~

## Rego
- [x] Google Calendar (Calendar.rego)
- [x] Groups for Business (Groups.rego)
- [x] Gmail (Gmail.rego)
- [x] Google Chat and Hangouts (Chat.rego)(Has Errors)
- [x] Google Drive and Docs (Drive.rego)
- [x] Google Meet (Meet.rego)(Has Errors)
- [x] Google Sites (Sites.rego)(Has Errors)
- [x] GWS Common Controls
- [x] ~Google Contacts~
