### ISSUE TITLE
Functional Testing - All Baselines

### ISSUE THREAD

**Issue by amart241** [cisagov/ScubaGoggles#80]
This epic covers the functional testing for all the baselines post the new baseline numbering format update and other revisions.

Key points:

- Test all the baseline policies
- Test different use cases and edge cases
     - For each policy verify if the output as expected when the tests pass/fail
     - For policies with multiple settings check that only the expected sub-policy will pass/fail and the other 
     dependent/independent policies are unaffected
- Perform tests to verify multiple OU and OU inheritance settings wherever applicable
- Perform tests to verify Group settings wherever applicable

Related issues

- [x] Chat - https://github.com/cisagov/ScubaGoggles/issues/78
- [x] Sites - https://github.com/cisagov/ScubaGoggles/issues/387
- [x] Calendar - https://github.com/cisagov/ScubaGoggles/issues/72
- [x] Classroom - https://github.com/cisagov/ScubaGoggles/issues/234
- [x] Gmail - https://github.com/cisagov/ScubaGoggles/issues/385
- [x] Common Controls - https://github.com/cisagov/ScubaGoggles/issues/92
- [x] Meet - https://github.com/cisagov/ScubaGoggles/issues/235
- [x] Groups - https://github.com/cisagov/ScubaGoggles/issues/236
- [x] Drive Docs - https://github.com/cisagov/ScubaGoggles/issues/386

**Comment by snarve** [comment]
Closing this issue as all baselines are functionally tested.
